CREATE TABLE IF NOT EXISTS intervolga_migrato_log(
	ID INT(11) NOT NULL AUTO_INCREMENT,
	MIGRATION_DATETIME datetime,
	TIMESTAMP_X timestamp not null default current_timestamp,
	MODULE_NAME VARCHAR(200),
	ENTITY_NAME VARCHAR(200),
	DATA_XML_ID VARCHAR(200),
	DATA_ID_NUM INT(11),
	DATA_ID_STR VARCHAR(200),
	DATA_ID_COMPLEX VARCHAR(500),
	STEP VARCHAR (200),
	OPERATION VARCHAR (200),
	RESULT INT(1),
	COMMENT VARCHAR(2000),
	PRIMARY KEY (ID)
);