<?php
namespace Intervolga\Migrato\Data\Module\Main;

use Bitrix\Main\Localization\Loc;
use Intervolga\Migrato\Data\BaseData;
use Intervolga\Migrato\Data\Record;

Loc::loadMessages(__FILE__);

class Agent extends BaseData
{
	/**
	 * @param string[] $filter
	 *
	 * @return \Intervolga\Migrato\Data\Record[]
	 */
	public function getList(array $filter = array())
	{
		$result = array();
		$agentsGetList = \CAgent::getList();
		while ($agent = $agentsGetList->fetch())
		{
			$record = new Record($this);
			$id = static::createId($agent['ID']);
			$record->setId($id);
			$record->setXmlId($this->getXmlId($id));
			$record->addFieldsRaw(array(
				'MODULE_ID' => $agent['MODULE_ID'],
				'NAME' => $agent['NAME'],
				'ACTIVE' => $agent['ACTIVE'],
				'AGENT_INTERVAL' => $agent['AGENT_INTERVAL'],
				'IS_PERIOD' => $agent['IS_PERIOD'],
			));
			$record->setId(static::createId($agent['ID']));

			$result[] = $record;
		}

		return $result;
	}

	public function getXmlId($id)
	{
		$agent = \CAgent::getById($id->getValue())->fetch();
		$agent['NAME'] = strtolower($agent['NAME']);
		$agent['NAME'] = str_replace('();', '', $agent['NAME']);
		$agent['NAME'] = str_replace(');', '', $agent['NAME']);
		$agent['NAME'] = str_replace('(', '_', $agent['NAME']);
		$agent['NAME'] = str_replace('::', '-', $agent['NAME']);
		$agent['NAME'] = preg_replace('/[^a-z0-9-_]/', '_', $agent['NAME']);
		$agent['NAME'] = ltrim($agent['NAME'], '_');
		return $agent['NAME'];
	}

	protected function createInner(Record $record)
	{
		$agent = $record->getFieldsRaw();
		$addRes = \CAgent::add($agent);
		if ($addRes)
		{
			return $this->createId($addRes);
		}
		else
		{
			throw $this->getApplicationException(Loc::getMessage('INTERVOLGA_MIGRATO.AGENT_UNKNOWN_ADD_ERROR'));
		}
	}

	public function update(Record $record)
	{
		$id = $this->findRecord($record->getXmlId());
		if ($id)
		{
			$agent = $record->getFieldsRaw();
			$updateRes = \CAgent::update($id->getValue(), $agent);
			if (!$updateRes)
			{
				throw $this->getApplicationException(Loc::getMessage('INTERVOLGA_MIGRATO.AGENT_UNKNOWN_UPDATE_ERROR'));
			}
			return $id;
		}
		else
		{
			throw new \Exception(Loc::getMessage('INTERVOLGA_MIGRATO.AGENT_NOT_FOUND'));
		}
	}

	protected function deleteInner($xmlId)
	{
		$id = $this->findRecord($xmlId);
		if ($id)
		{
			$deleteRes = \CAgent::delete($id->getValue());
			if (!$deleteRes)
			{
				throw $this->getApplicationException(Loc::getMessage('INTERVOLGA_MIGRATO.AGENT_UNKNOWN_DELETE_ERROR'));
			}
		}
	}

	public function setXmlId($id, $xmlId)
	{
		// XML ID is autogenerated, cannot be modified
	}

	/**
	 * @param string $defaultMessage
	 *
	 * @return \Exception
	 */
	protected function getApplicationException($defaultMessage = '')
	{
		global $APPLICATION;
		if ($exception = $APPLICATION->getException())
		{
			$message = $exception->getString();
		}
		else
		{
			$message = $defaultMessage;
		}

		return new \Exception($message);
	}
}