<?
namespace Intervolga\Migrato\Data\Module\Main;


use Bitrix\Main\Localization\Loc;
use Intervolga\Migrato\Data\BaseData;
use Intervolga\Migrato\Data\Link;
use Intervolga\Migrato\Data\Record;
use Intervolga\Migrato\Data\RecordId;

class GroupRights extends BaseData
{
	const ALL_USERS_GROUP_ID = 2;
	const XML_ID_DELIMITER = '_';

	protected function configure()
	{
		$this->setEntityNameLoc(Loc::getMessage('INTERVOLGA_MIGRATO.MAIN_GROUP_RIGHT'));
		$this->setFilesSubdir('/');
		$this->setDependencies(array(
			'GROUP' => new Link(Group::getInstance()),
			'TASK' => new Link(Task::getInstance()),
		));
	}

	/**
	 * @param string[] $filter
	 *
	 * @return \Intervolga\Migrato\Data\Record[]
	 */
	public function getList(array $filter = array())
	{
		//Получить список всех групп пользователей
		$rsGroups = \CGroup::GetList($by="ID", $order="asc", array("ADMIN"=>'N')); // выбираем группы
		$groups = array();
		while($g = $rsGroups->Fetch())
		{
			if($g['ID'] != ALL_USERS_GROUP_ID)
				$groups["ID"] = $g['ID'];
				$groups["STRING_ID"] = $g['STRING_ID'];
		}
		//Получить список всех модулей
		$rsInstalledModules = \CModule::GetList();
		$result = array();
		foreach ($groups as $groupId) {
			$record = new Record($this);
			$record->setId($this->createId($groupId["STRING_ID"]));
			$record->setXmlId($this->createXmlId($groupId["STRING_ID"]));
			$fields = array();
			$dependencylist = array();
			while ($m = $rsInstalledModules->Fetch()){
				$moduleId = $m['ID'];
				$roles = \CMain::GetUserRoles($moduleId, array($groupId["ID"]),'N');
				if($roles) {
//					var_dump(array($roles,$moduleId,$groupId["ID"]));
					$tasksId = array();
					$dbRes = \CTask::GetList(array(), array(
						'MODULE_ID' => $moduleId
					));
					while ($task = $dbRes->fetch()) {
						if (in_array($task['LETTER'], $roles)) {
							$tasksId[] = $task['ID'];
						}
					}
					if ($tasksId) {
						$dependencylist[$moduleId] = $tasksId;
					}
					else{
						$fields[$moduleId] = $moduleId."___".$roles[0];
					}

				}
			}
			$record->addFieldsRaw(array(
				'CODE_RIGHT' => $fields,
			));
			$this->addGroupDependency($record, $groupId);
			$this->addTaskDependency($record, $dependencylist);
			$result[] = $record;
		}
		return $result;
	}

	/**
	 * @param \Intervolga\Migrato\Data\Record $record
	 * @param $groupId
	 */
	private function addGroupDependency($record, $groupId)
	{
		$groupLink = clone($this->getDependency('GROUP'));
		$groupRecordId = Group::getInstance()->createId($groupId);
		$groupLink->setValue($groupRecordId->getValue());
		$record->setDependency('GROUP', $groupLink);
	}

	/**
	 * @param \Intervolga\Migrato\Data\Record $record
	 * @param $taskId
	 */
	private function addTaskDependency($record,array $tasksId)
	{
		$taskLinks =array();
		foreach ($tasksId as $ID=>$taskId)
		{
			$taskLink = clone($this->getDependency('TASK'));
			$taskLink->setValue(Task::getInstance()->getXmlId($taskId[0]));
			$taskLinks[$ID] = $taskLink;
//			$record->setDependency("RIGHT[]",$taskLink);
		}
		$record->setDependencies($taskLinks);
	}

	/**
	 * @param \Intervolga\Migrato\Data\Record $record
	 *
	 * @throws \Bitrix\Main\NotImplementedException
	 */
	public function update(Record $record)
	{
		parent::update($record); // TODO: Change the autogenerated stub
	}

	/**
	 * @param \Intervolga\Migrato\Data\Record $record
	 *
	 * @throws \Bitrix\Main\NotImplementedException
	 *
	 * @return \Intervolga\Migrato\Data\RecordId
	 */
	protected function createInner(Record $record)
	{
		parent::createInner($record); // TODO: Change the autogenerated stub
	}

	/**
	 * @param \Intervolga\Migrato\Data\RecordId $id
	 *
	 * @throws \Bitrix\Main\NotImplementedException
	 */
	protected function deleteInner(RecordId $id)
	{
		parent::deleteInner($id); // TODO: Change the autogenerated stub
	}

	/**
	 * @param string $xmlId
	 *
	 * @return \Intervolga\Migrato\Data\RecordId|null
	 */
	public function findRecord($xmlId)
	{
		$delPos = strpos ($xmlId , static::XML_ID_DELIMITER);
		if($delPos)
		{
			$moduleId = substr($xmlId, 0, $delPos);
			$groupXmlId = substr($xmlId, $delPos+1);
			$groupRecId = Group::getInstance()->findRecord($groupXmlId);
			$groupId = $groupRecId->getValue();
			if(\CMain::GetUserRoles($moduleId, array($groupId),'N'))
			{
				return $this->createId(array(
					'MODULE_ID'=>$moduleId,
					'GROUP_ID'=>$groupId)
				);
			}
			return null;
		}
	}

	/**
	 * @param \Intervolga\Migrato\Data\RecordId $id
	 * @param string $xmlId
	 *
	 * @throws \Bitrix\Main\NotImplementedException
	 */
	public function setXmlId($id, $xmlId)
	{
		parent::setXmlId($id, $xmlId); // TODO: Change the autogenerated stub
	}

	/**
	 * @param \Intervolga\Migrato\Data\RecordId $id
	 *
	 * @return string
	 * @throws \Bitrix\Main\NotImplementedException
	 */
	public function getXmlId($id)
	{
		$data = $id->getValue();
		return $this->createXmlId($data);
	}

	private function createXmlId($data)
	{
		return ($data['MODULE_ID'].static::XML_ID_DELIMITER.Group::getInstance()->getXmlId(Group::getInstance()->createId(intval($data['GROUP_ID']))));
	}


	public function createId($id)
	{
		return RecordId::createComplexId(array(
				"MODULE_ID" => $id['MODULE_ID'],
				"GROUP_ID" => $id['GROUP_ID']
			)
		);
	}
}